# Generated by Django 6.0.3 on 2026-04-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID пациента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предсказания')),
                ('predicted_label', models.CharField(max_length=255, verbose_name='Предсказанный класс')),
                ('confidence', models.FloatField(verbose_name='Уверенность (%)')),
                ('top_genes', models.JSONField(default=dict, verbose_name='Топ-10 генов')),
                ('alternatives', models.JSONField(default=list, verbose_name='Альтернативы')),
                ('input_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла')),
            ],
            options={
                'verbose_name': 'Предсказание',
                'verbose_name_plural': 'История предсказаний',
                'ordering': ['-created_at'],
            },
        ),
    ]
