# Generated by Django 6.0.3 on 2026-05-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionhistory',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
