# Generated by Django 6.0.3 on 2026-05-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_predictionhistory_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerLabelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=255, unique=True)),
                ('russian_name', models.CharField(max_length=255)),
            ],
        ),
    ]
